### ISSUE TITLE
Upgrade go.mod dependencies to get security updates

### ISSUE THREAD

**Issue by jhonis** [ChistaDATA/cluster-secret-operator#10]
## Dependabot security alerts
https://github.com/ChistaDATA/cluster-secret-operator/security/dependabot/1
https://github.com/ChistaDATA/cluster-secret-operator/security/dependabot/2
https://github.com/ChistaDATA/cluster-secret-operator/security/dependabot/3

**Comment by biju-s** [comment]
[PR](https://github.com/ChistaDATA/cluster-secret-operator/pull/11) approved
